# Generated by Django 5.2.13 on 2026-07-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_notification_payload_alter_notification_verb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="has_had_tour",
            new_name="has_had_introduction",
        ),
    ]
