# Generated by Django 5.2.13 on 2026-06-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0004_project_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abikasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.PositiveIntegerField()),
                ("current", models.PositiveIntegerField()),
            ],
        ),
    ]
