# Generated by Django 5.2.13 on 2026-07-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0004_backfill_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="external_mail",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
