# Generated by Django 5.2.13 on 2026-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0005_userprofile_external_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
