# Generated by Django 5.2.13 on 2026-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0005_abikasse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abikasse",
            name="current",
            field=models.IntegerField(),
        ),
    ]
