# Generated by Django 5.2.13 on 2026-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0007_project_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="final",
            field=models.BooleanField(default=False),
        ),
    ]
