# Generated by Django 5.2.13 on 2026-07-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abi", "0009_notification"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="project",
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added_to_project", "Added to project"),
                    ("removed_from_project", "Removed from project"),
                ],
                default="added_to_project",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
